### ISSUE TITLE
About the deployment environment

### ISSUE THREAD

**Issue by OpsNullPointerException** [Status-Changer/Docker#18]
I can't run it on my machine, the operating system is cenots 7.6, I tried many solutions, but it still doesn't work. I want to know if I should use a specific operating system.

**Comment by Status-Changer** [comment]
Yes, the OS the author suggested is Ubuntu 14.04 (yes, a deprecated version because of the file system AUFS)
CentOS is of course better in many cases, but not here :)

**Comment by Status-Changer** [comment]
If there're no more questions about deployment, environment or version, I'll close this issue tonight.
Thank you for your attention.
